spring:
  data:
    mongodb:
      uri: mongodb+srv://karnaeze:Paddu4408@azure-karan-db.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      database: azure-karan-db


